// <auto-generated />
using System;
using Infra.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201104173146_Fenacon")]
    partial class Fenacon
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fenacon.Dominio.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CargaHoraria")
                        .HasColumnName("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("Cargo")
                        .HasColumnName("CargoFuncionario")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("CpfFuncionario")
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnName("DataAdmissao")
                        .HasColumnType("dateTime");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnName("EnderecoFuncionario")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NomeFuncionario")
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Situacao")
                        .HasColumnName("Situacao")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Fenacon.Dominio.Funcionario", b =>
                {
                    b.HasOne("Fenacon.Dominio.Funcionario", "Supervisor")
                        .WithMany("Subordinados")
                        .HasForeignKey("SupervisorId");
                });
#pragma warning restore 612, 618
        }
    }
}
